# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gusen/code/kmer/QuickKmer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gusen/code/kmer/QuickKmer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gusen/code/kmer/QuickKmer/CMakeFiles /Users/gusen/code/kmer/QuickKmer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gusen/code/kmer/QuickKmer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kmer

# Build rule for target.
kmer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kmer
.PHONY : kmer

# fast build rule for target.
kmer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/build
.PHONY : kmer/fast

src/CompressDate.o: src/CompressDate.cpp.o
.PHONY : src/CompressDate.o

# target to build an object file
src/CompressDate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/CompressDate.cpp.o
.PHONY : src/CompressDate.cpp.o

src/CompressDate.i: src/CompressDate.cpp.i
.PHONY : src/CompressDate.i

# target to preprocess a source file
src/CompressDate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/CompressDate.cpp.i
.PHONY : src/CompressDate.cpp.i

src/CompressDate.s: src/CompressDate.cpp.s
.PHONY : src/CompressDate.s

# target to generate assembly for a file
src/CompressDate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/CompressDate.cpp.s
.PHONY : src/CompressDate.cpp.s

src/head.o: src/head.cpp.o
.PHONY : src/head.o

# target to build an object file
src/head.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/head.cpp.o
.PHONY : src/head.cpp.o

src/head.i: src/head.cpp.i
.PHONY : src/head.i

# target to preprocess a source file
src/head.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/head.cpp.i
.PHONY : src/head.cpp.i

src/head.s: src/head.cpp.s
.PHONY : src/head.s

# target to generate assembly for a file
src/head.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/head.cpp.s
.PHONY : src/head.cpp.s

src/index.o: src/index.cpp.o
.PHONY : src/index.o

# target to build an object file
src/index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/index.cpp.o
.PHONY : src/index.cpp.o

src/index.i: src/index.cpp.i
.PHONY : src/index.i

# target to preprocess a source file
src/index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/index.cpp.i
.PHONY : src/index.cpp.i

src/index.s: src/index.cpp.s
.PHONY : src/index.s

# target to generate assembly for a file
src/index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/index.cpp.s
.PHONY : src/index.cpp.s

src/out.o: src/out.cpp.o
.PHONY : src/out.o

# target to build an object file
src/out.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/out.cpp.o
.PHONY : src/out.cpp.o

src/out.i: src/out.cpp.i
.PHONY : src/out.i

# target to preprocess a source file
src/out.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/out.cpp.i
.PHONY : src/out.cpp.i

src/out.s: src/out.cpp.s
.PHONY : src/out.s

# target to generate assembly for a file
src/out.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kmer.dir/build.make CMakeFiles/kmer.dir/src/out.cpp.s
.PHONY : src/out.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... kmer"
	@echo "... src/CompressDate.o"
	@echo "... src/CompressDate.i"
	@echo "... src/CompressDate.s"
	@echo "... src/head.o"
	@echo "... src/head.i"
	@echo "... src/head.s"
	@echo "... src/index.o"
	@echo "... src/index.i"
	@echo "... src/index.s"
	@echo "... src/out.o"
	@echo "... src/out.i"
	@echo "... src/out.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

